name: Deploy

on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicates"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}

       - name: Set git configs
         continue-on-error: true
         run: |
           git config --global user.email ${{ secrets.GITHUBMAIL }}
           git config --global user.name ${{ secrets.GITHUBNAME }}
           git config --global credential.helper store
           echo "https://${{ secrets.GITHUBNAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

       - name: Cloning the repo
         continue-on-error: true
         run: |
           git clone -b dev https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_NAME }}/test.git

       - name: Running the bot
         timeout-minutes: 300
         continue-on-error: true
         run: |
           cd test
           docker build -t test . && docker run test

       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
